version: "3.8"
services:
  client:
    container_name: "sparkplug_web"
    depends_on:
      - "server"
    build: ./client
    ports:
      - "$WEB_PORT:3000"
  server:
    container_name: "sparkplug_host"
    restart: unless-stopped
    command: "./build/home_sparkplug_host $BROKER_ADDRESS"
    build: ./server
    ports:
      - "$WEBSOCKET_PORT:9000"
